on: [push]

jobs:
  simple_test_job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
    - name: Hello world action step
      id: hello
      uses: Bouncner/hyrise_workload_analysis_plugin
